import { defineField, defineType } from "sanity";

export const wallOfLoveVote = defineType({
  name: "wallOfLoveVote",
  title: "Wall of Love — Vote",
  type: "document",
  fields: [
    defineField({
      name: "restaurantId",
      title: "Restaurant ID",
      type: "string",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "voteType",
      title: "Vote Type",
      description: "upvote or downvote",
      type: "string",
      validation: (rule) =>
        rule.required().custom((v) =>
          v === "upvote" || v === "downvote"
            ? true
            : { message: "Must be upvote or downvote" }
        ),
    }),
    defineField({
      name: "fingerprint",
      title: "Browser Fingerprint",
      description:
        "Generated by FingerprintJS. Stable across incognito and localStorage clears.",
      type: "string",
    }),
    defineField({
      name: "ip",
      title: "IP Address",
      type: "string",
    }),
    defineField({
      name: "month",
      title: "Month",
      type: "string",
    }),
    defineField({
      name: "votedAt",
      title: "Voted At",
      type: "datetime",
      initialValue: () => new Date().toISOString(),
    }),
  ],

  preview: {
    select: {
      title: "restaurantId",
      subtitle: "voteType",
    },
  },
});
